#pragma once

#define BINDING_KEY_QUIT VK_F12

#define BINDING_P1_FL 'Q'
#define BINDING_P1_FC 'W'
#define BINDING_P1_FR 'E'
#define BINDING_P1_CL 'A'
#define BINDING_P1_CC 'S'
#define BINDING_P1_CR 'D'
#define BINDING_P1_RL 'Z'
#define BINDING_P1_RC 'X'
#define BINDING_P1_RR 'C'

#define BINDING_P2_FL VK_NUMPAD7
#define BINDING_P2_FC VK_NUMPAD8
#define BINDING_P2_FR VK_NUMPAD9
#define BINDING_P2_CL VK_NUMPAD4
#define BINDING_P2_CC VK_NUMPAD5
#define BINDING_P2_CR VK_NUMPAD6
#define BINDING_P2_RL VK_NUMPAD1
#define BINDING_P2_RC VK_NUMPAD2
#define BINDING_P2_RR VK_NUMPAD3

#define BINDING_BUTTON_LL '1'
#define BINDING_BUTTON_LC '2'
#define BINDING_BUTTON_LR '3'

#define BINDING_BUTTON_CL VK_LEFT
#define BINDING_BUTTON_CC VK_RETURN
#define BINDING_BUTTON_CR VK_RIGHT

#define BINDING_BUTTON_RL '4'
#define BINDING_BUTTON_RC '5'
#define BINDING_BUTTON_RR '6'

#define BINDING_COIN_1  VK_F3
#define BINDING_COIN_2  VK_F4
#define BINDING_TEST    VK_F2
#define BINDING_SERVICE VK_F1
